### PR TITLE
fix(sequelize): Adds postgres to the dbUtils

### LINKED ISSUE #8: dbUtils does not provide a proper connection to any other databases besides mySql
dbUtils is specific to mySql connections only.  To support Postgres at the least there needs to be an additional set of utilities or to remove the references to dbUtils from SequelizeManager.js and utils.js

### PR DESCRIPTION
**Pull request by PWKad**
Fixes #8.  This is a work in process because I can't get the tests to set up properly
I've included a starting point for the tests.

### CODE REVIEW

**Comment by PWKad** [comment]
@jtraband I could not get the mocha tests running to verify the tests are passing so if you can give me some quick setup tips on how you are resolving `breeze-sequelize` I can go back and verify.  I did not yet add the dependency to the package.json for `pg` either.

**Comment by jtraband** [comment]
@PWKad I've asked one of the other engineers here to take a look and get back to you on your questions. He's also going to convert our node/sequelize ToDo sample to work with Postgres.  He should be posting here soon.  and again thanks for spending the time.

**Comment by dkoswara** [comment]
@PWKad looks like we may have forgotten to add the `breeze-sequelize` package dependency to the package.json. Please add this manually and let me know if you're able to run the tests.

**Comment by PWKad** [comment]
@dkoswara Sure, wouldn't that be self-referencing though?  I would want the test to check the local instance.

**Comment by dkoswara** [comment]
@PWKad, sorry, I misunderstood your intention just now. I'm also not sure how the tests are getting the local `breeze-sequelize` instance. Let me see what I can find out and get back to you.

**Comment by PWKad** [comment]
Cool thanks!  I'll continue on with the other issues.

**Comment by dkoswara** [comment]
@PWKad, you can use the [npm link](https://docs.npmjs.com/cli/link) command to link/install a local package.

**Comment by PWKad** [comment]
I've tried to use the `npm link` command but it seems a bit self-referencing.  I think the test that needs it only really needs the db utils file anyway, but I'm still unable to get it to run properly.  I've also noticed some other issues that are blocking this from working  - @dkoswara would you like me to continue to open issues here for things I run in to or wait until you have a sample app running?  I'd like to use this as a full stack sample app for `aurelia` and `breeze` integration.  I've been working on finding the best workflow for a few weeks and I think this will play very nicely together.

**Comment by dkoswara** [comment]
@PWKad, please continue to open (separate) issues here for things that you run into. I too have encountered issues when using your changes to the dbutils in creating the sample app with postgres. In the end, I chose to use sql scripts to create and populate the sample db.

The sample can be reviewed at 

https://github.com/Breeze/breeze.js.samples/tree/feature/todo-angular-node-postgres/node/todo-angular

One big known issue is that the `breeze-sequelize` libary doesn't currently work with Sequelize version `2.0.0` and above. The most recent version it can work with is Sequelize `2.0.0-rc8`. This may be the root cause of the other issues that we've seen since we can't upgrade to the latest Sequelize.

**Comment by steveschmitt** [comment]
Thanks for the pull request.  It shows that we need a better way to manage the dependencies on different databases.

**Pull request merged**
