### PR TITLE
fix(sequelize): autoGeneratedKeyType Identity in MetadataMapper

### LINKED ISSUE #11: breeze-sequelize autoGeneratedKeyType Identity not working
The configuration `"autoGeneratedKeyType": "Identity"` is currently not working because the `autoIncrement` attribute will never get set in the current `MetadataMapper` with the sequelize version 2.1.3+. 

I've also created and Stackoverflow post before i found this issue: http://stackoverflow.com/questions/31704458/breeze-sequelize-with-autogeneratedkeytype-identity/31721538#31721538

In the `MetadataMapper` the `type` attribute is defined via the `_dataTypeMap`, which will return e.g. `Sequelize.INTEGER` for `Int32` and then there is an if statement like this:
```
if (attributes.type == "INTEGER" || attributes.type == "BIGINT") {
   attributes.autoIncrement = true;
}
```
Though `Sequelize.INTEGER` is not a string at all, so the `autoIncrement` attribute will never be true.

### PR DESCRIPTION
**Pull request by JuHwon**
Fixes #11.

### CODE REVIEW

**Comment by JuHwon** [comment]
@wardbell @jtraband any updates on this?

**Comment by wardbell** [comment]
We're a little behind at the moment and we have a week of vacation coming up. Please hang in there.

**Comment by drewhawken** [comment]
@wardbell @jtraband any updates on this, holding up development unless I put a hack in place to fix it.

**Comment by JuHwon** [comment]
@wardbell @jtraband is there any plan continuing development in this project? Sorry, though to me it looks like a "dead" project. I really love the work you guys have done! I need to make a decision if i am still building on breezejs in further projects. Right now i am not confident building apps with breezejs, due to the low activity.

**Comment by steveschmitt** [comment]
Not dead!  Like most OSS developers, we have to balance the time we spend developing the framework with the time we spend using it on projects.  

Sorry about the delay.  We'll try to be more active.

**Comment by JuHwon** [comment]
Thank you very much for your respond. Good to hear that! Looking forward to work with breezeJS :)

**Comment by drewhawken** [comment]
Thanks @steveschmitt and @JuHwon for pushing to get this fixed, I have been building a new backend framework suite of apps and was concerned about having to manually patch this issue.

**Pull request merged**
